# ma20260826/services/sector_stock_foreign_service.py
from __future__ import annotations

from typing import TYPE_CHECKING

from utils.logger import get_logger

if TYPE_CHECKING:
    from models.stock_model import StockModel

logger = get_logger(__name__)


class SectorStockForeignService:
    """
    Сервис определения страны и сектора для зарубежных акций MOEX.

    Источник:

        внутренний COUNTRY_SECTOR_MAP


    Заполняет:

        StockModel.country
        StockModel.sector


    Не изменяет:

        secid
        isin


    В будущем источник можно заменить:

        - Finam API
        - MOEX API
        - Excel
        - PostgreSQL
        - ClickHouse
    """

    UNKNOWN_COUNTRY = "Неизвестно"
    UNKNOWN_SECTOR = "Неизвестно"

    # Словарь для перевода секторов GICS на русский язык
    GICS_TO_RUSSIAN = {
        "Health Care": "Здравоохранение",
        "Materials": "Материалы",
        "Industrials": "Промышленность",
        "Information Technology": "Информационные технологии",
        "Consumer Discretionary": "Потребительские товары длительного пользования",
        "Consumer Staples": "Потребительские товары повседневного спроса",
        "Utilities": "Коммунальные услуги",
        "Financials": "Финансы",
        "Energy": "Энергетика",
        "Communication Services": "Связь",
        "Real Estate": "Недвижимость",
        "ETF": "ETF",  # Оставляем как есть
    }

    # Основной маппинг: SECID -> (Страна, Сектор GICS)
    COUNTRY_SECTOR_MAP = {
        "A-RM": ("США", "Health Care"),
        "AA-RM": ("США", "Materials"),
        "AAL-RM": ("США", "Industrials"),
        "AAPL-RM": ("США", "Information Technology"),
        "ABBV-RM": ("США", "Health Care"),
        "ABNB-RM": ("США", "Consumer Discretionary"),
        "ABT-RM": ("США", "Health Care"),
        "ACAD-RM": ("США", "Health Care"),
        "ADBE-RM": ("США", "Information Technology"),
        "ADI-RM": ("США", "Information Technology"),
        "ADM-RM": ("США", "Consumer Staples"),
        "ADP-RM": ("США", "Industrials"),
        "ADSK-RM": ("США", "Information Technology"),
        "AEE-RM": ("США", "Utilities"),
        "AEO-RM": ("США", "Consumer Discretionary"),
        "AES-RM": ("США", "Utilities"),
        "AFL-RM": ("США", "Financials"),
        "AIG-RM": ("США", "Financials"),
        "AJG-RM": ("США", "Financials"),
        "AKAM-RM": ("США", "Information Technology"),
        "ALB-RM": ("США", "Materials"),
        "ALK-RM": ("США", "Industrials"),
        "ALL-RM": ("США", "Financials"),
        "ALLY-RM": ("США", "Financials"),
        "AMD-RM": ("США", "Information Technology"),
        "AME-RM": ("США", "Industrials"),
        "AMGN-RM": ("США", "Health Care"),
        "AMP-RM": ("США", "Financials"),
        "AMZN-RM": ("США", "Consumer Discretionary"),
        "AOS-RM": ("США", "Industrials"),
        "APA-RM": ("США", "Energy"),
        "APD-RM": ("США", "Materials"),
        "APH-RM": ("США", "Information Technology"),
        "APP-RM": ("США", "Information Technology"),
        "APPS-RM": ("США", "Information Technology"),
        "ARCC-RM": ("США", "Financials"),
        "AT-RM": ("США", "Communication Services"),
        "ATO-RM": ("США", "Utilities"),
        "ATUS-RM": ("США", "Communication Services"),
        "AVGO-RM": ("США", "Information Technology"),
        "AWK-RM": ("США", "Utilities"),
        "AXP-RM": ("США", "Financials"),
        "AXSM-RM": ("США", "Health Care"),
        "AZO-RM": ("США", "Consumer Discretionary"),
        "BABA-RM": ("Китай", "Consumer Discretionary"),
        "BAC-RM": ("США", "Financials"),
        "BAX-RM": ("США", "Health Care"),
        "BBWI-RM": ("США", "Consumer Discretionary"),
        "BBY-RM": ("США", "Consumer Discretionary"),
        "BDX-RM": ("США", "Health Care"),
        "BEN-RM": ("США", "Financials"),
        "BFB-RM": ("США", "Consumer Staples"),
        "BGS-RM": ("США", "Consumer Staples"),
        "BIDU-RM": ("Китай", "Communication Services"),
        "BIIB-RM": ("США", "Health Care"),
        "BILI-RM": ("Китай", "Communication Services"),
        "BIO-RM": ("США", "Health Care"),
        "BK-RM": ("США", "Financials"),
        "BKNG-RM": ("США", "Consumer Discretionary"),
        "BKR-RM": ("США", "Energy"),
        "BLNK-RM": ("США", "Industrials"),
        "BMY-RM": ("США", "Health Care"),
        "BOX-RM": ("США", "Information Technology"),
        "BP-RM": ("Великобритания", "Energy"),
        "BRKB-RM": ("США", "Financials"),
        "BSX-RM": ("США", "Health Care"),
        "BWA-RM": ("США", "Consumer Discretionary"),
        "BYND-RM": ("США", "Consumer Staples"),
        "C-RM": ("США", "Financials"),
        "CAG-RM": ("США", "Consumer Staples"),
        "CAH-RM": ("США", "Health Care"),
        "CARG-RM": ("США", "Communication Services"),
        "CARR-RM": ("США", "Industrials"),
        "CAT-RM": ("США", "Industrials"),
        "CC-RM": ("США", "Materials"),
        "CDNS-RM": ("США", "Information Technology"),
        "CE-RM": ("США", "Materials"),
        "CF-RM": ("США", "Materials"),
        "CFG-RM": ("США", "Financials"),
        "CHD-RM": ("США", "Consumer Staples"),
        "CHRW-RM": ("США", "Industrials"),
        "CHWY-RM": ("США", "Consumer Discretionary"),
        "CI-RM": ("США", "Health Care"),
        "CINF-RM": ("США", "Financials"),
        "CL-RM": ("США", "Consumer Staples"),
        "CLF-RM": ("США", "Materials"),
        "CLOV-RM": ("США", "Health Care"),
        "CLSK-RM": ("США", "Information Technology"),
        "CLX-RM": ("США", "Consumer Staples"),
        "CMA-RM": ("США", "Financials"),
        "CMCSA-RM": ("США", "Communication Services"),
        "CME-RM": ("США", "Financials"),
        "CMI-RM": ("США", "Industrials"),
        "CMS-RM": ("США", "Utilities"),
        "CNC-RM": ("США", "Health Care"),
        "CNK-RM": ("США", "Communication Services"),
        "CNP-RM": ("США", "Utilities"),
        "CNX-RM": ("США", "Energy"),
        "COF-RM": ("США", "Financials"),
        "COHR-RM": ("США", "Information Technology"),
        "COP-RM": ("США", "Energy"),
        "COST-RM": ("США", "Consumer Staples"),
        "COTY-RM": ("США", "Consumer Staples"),
        "COUR-RM": ("США", "Consumer Discretionary"),
        "CPNG-RM": ("Южная Корея", "Consumer Discretionary"),
        "CPRT-RM": ("США", "Industrials"),
        "CRM-RM": ("США", "Information Technology"),
        "CROX-RM": ("США", "Consumer Discretionary"),
        "CRWD-RM": ("США", "Information Technology"),
        "CSCO-RM": ("США", "Information Technology"),
        "CSGP-RM": ("США", "Real Estate"),
        "CSX-RM": ("США", "Industrials"),
        "CTAS-RM": ("США", "Industrials"),
        "CTSH-RM": ("США", "Information Technology"),
        "CTVA-RM": ("США", "Materials"),
        "CVNA-RM": ("США", "Consumer Discretionary"),
        "CVS-RM": ("США", "Health Care"),
        "CVX-RM": ("США", "Energy"),
        "D-RM": ("США", "Utilities"),
        "DAL-RM": ("США", "Industrials"),
        "DAR-RM": ("США", "Consumer Staples"),
        "DASH-RM": ("США", "Consumer Discretionary"),
        "DBX-RM": ("США", "Information Technology"),
        "DDOG-RM": ("США", "Information Technology"),
        "DE-RM": ("США", "Industrials"),
        "DELL-RM": ("США", "Information Technology"),
        "DG-RM": ("США", "Consumer Staples"),
        "DGX-RM": ("США", "Health Care"),
        "DHI-RM": ("США", "Consumer Discretionary"),
        "DIS-RM": ("США", "Communication Services"),
        "DOCS-RM": ("США", "Health Care"),
        "DOCU-RM": ("США", "Information Technology"),
        "DOV-RM": ("США", "Industrials"),
        "DOW-RM": ("США", "Materials"),
        "DRI-RM": ("США", "Consumer Discretionary"),
        "DT-RM": ("США", "Information Technology"),
        "DUK-RM": ("США", "Utilities"),
        "DVN-RM": ("США", "Energy"),
        "DXCM-RM": ("США", "Health Care"),
        "EBAY-RM": ("США", "Consumer Discretionary"),
        "ED-RM": ("США", "Utilities"),
        "EDIT-RM": ("США", "Health Care"),
        "EGHT-RM": ("США", "Information Technology"),
        "EHTH-RM": ("США", "Health Care"),
        "EIX-RM": ("США", "Utilities"),
        "EL-RM": ("США", "Consumer Staples"),
        "ELV-RM": ("США", "Health Care"),
        "EMR-RM": ("США", "Industrials"),
        "ENPH-RM": ("США", "Information Technology"),
        "EOG-RM": ("США", "Energy"),
        "EQT-RM": ("США", "Energy"),
        "ES-RM": ("США", "Utilities"),
        "ETR-RM": ("США", "Utilities"),
        "ETSY-RM": ("США", "Consumer Discretionary"),
        "EVRG-RM": ("США", "Utilities"),
        "EW-RM": ("США", "Health Care"),
        "EXC-RM": ("США", "Utilities"),
        "EXEL-RM": ("США", "Health Care"),
        "EXPE-RM": ("США", "Consumer Discretionary"),
        "F-RM": ("США", "Consumer Discretionary"),
        "FANG-RM": ("США", "Energy"),
        "FAST-RM": ("США", "Industrials"),
        "FCX-RM": ("США", "Materials"),
        "FDX-RM": ("США", "Industrials"),
        "FDXF-RM": ("США", "Industrials"),
        "FE-RM": ("США", "Utilities"),
        "FFIV-RM": ("США", "Information Technology"),
        "FI-RM": ("США", "Information Technology"),
        "FIRY-RM": ("США", "Communication Services"),
        "FIS-RM": ("США", "Information Technology"),
        "FITB-RM": ("США", "Financials"),
        "FIVN-RM": ("США", "Information Technology"),
        "FLNA-RM": ("США", "Health Care"),
        "FLO-RM": ("США", "Consumer Staples"),
        "FLR-RM": ("США", "Industrials"),
        "FMC-RM": ("США", "Materials"),
        "FNF-RM": ("США", "Financials"),
        "FNKO-RM": ("США", "Consumer Discretionary"),
        "FOX-RM": ("США", "Communication Services"),
        "FRHC-RM": ("США", "Financials"),
        "FSLR-RM": ("США", "Information Technology"),
        "FSLY-RM": ("США", "Information Technology"),
        "FTNT-RM": ("США", "Information Technology"),
        "GDDY-RM": ("США", "Information Technology"),
        "GDRX-RM": ("США", "Health Care"),
        "GEN-RM": ("США", "Information Technology"),
        "GEV-RM": ("США", "Industrials"),
        "GEVO-RM": ("США", "Materials"),
        "GILD-RM": ("США", "Health Care"),
        "GIS-RM": ("США", "Consumer Staples"),
        "GLW-RM": ("США", "Information Technology"),
        "GOOG-RM": ("США", "Communication Services"),
        "GOOGL-RM": ("США", "Communication Services"),
        "GPC-RM": ("США", "Consumer Discretionary"),
        "GPS-RM": ("США", "Consumer Discretionary"),
        "GS-RM": ("США", "Financials"),
        "GT-RM": ("США", "Consumer Discretionary"),
        "HAL-RM": ("США", "Energy"),
        "HAS-RM": ("США", "Consumer Discretionary"),
        "HBAN-RM": ("США", "Financials"),
        "HCA-RM": ("США", "Health Care"),
        "HD-RM": ("США", "Consumer Discretionary"),
        "HIG-RM": ("США", "Financials"),
        "HOG-RM": ("США", "Consumer Discretionary"),
        "HOOD-RM": ("США", "Financials"),
        "HPE-RM": ("США", "Information Technology"),
        "HPQ-RM": ("США", "Information Technology"),
        "HRB-RM": ("США", "Industrials"),
        "HRL-RM": ("США", "Consumer Staples"),
        "HRTX-RM": ("США", "Health Care"),
        "HSY-RM": ("США", "Consumer Staples"),
        "HWM-RM": ("США", "Industrials"),
        "HYLN-RM": ("США", "Industrials"),
        "IBM-RM": ("США", "Information Technology"),
        "ICE-RM": ("США", "Financials"),
        "IDXX-RM": ("США", "Health Care"),
        "ILMN-RM": ("США", "Health Care"),
        "INCY-RM": ("США", "Health Care"),
        "INTC-RM": ("США", "Information Technology"),
        "INTU-RM": ("США", "Information Technology"),
        "IONS-RM": ("США", "Health Care"),
        "IOVA-RM": ("США", "Health Care"),
        "IP-RM": ("США", "Materials"),
        "IR-RM": ("США", "Industrials"),
        "ISRG-RM": ("США", "Health Care"),
        "IT-RM": ("США", "Information Technology"),
        "ITW-RM": ("США", "Industrials"),
        "JD-RM": ("Китай", "Consumer Discretionary"),
        "JEF-RM": ("США", "Financials"),
        "JNJ-RM": ("США", "Health Care"),
        "JPM-RM": ("США", "Financials"),
        "KD-RM": ("США", "Information Technology"),
        "KDP-RM": ("США", "Consumer Staples"),
        "KEY-RM": ("США", "Financials"),
        "KHC-RM": ("США", "Consumer Staples"),
        "KKR-RM": ("США", "Financials"),
        "KLAC-RM": ("США", "Information Technology"),
        "KMB-RM": ("США", "Consumer Staples"),
        "KMI-RM": ("США", "Energy"),
        "KMX-RM": ("США", "Consumer Discretionary"),
        "KNX-RM": ("США", "Industrials"),
        "KO-RM": ("США", "Consumer Staples"),
        "KOPN-RM": ("США", "Information Technology"),
        "KR-RM": ("США", "Consumer Staples"),
        "KWEB-RM": ("Китай", "ETF"),
        "LEG-RM": ("США", "Consumer Discretionary"),
        "LI-RM": ("Китай", "Consumer Discretionary"),
        "LKQ-RM": ("США", "Consumer Discretionary"),
        "LLY-RM": ("США", "Health Care"),
        "LNT-RM": ("США", "Utilities"),
        "LOW-RM": ("США", "Consumer Discretionary"),
        "LUMN-RM": ("США", "Communication Services"),
        "LUV-RM": ("США", "Industrials"),
        "LVS-RM": ("США", "Consumer Discretionary"),
        "LYFT-RM": ("США", "Consumer Discretionary"),
        "M-RM": ("США", "Consumer Discretionary"),
        "MA-RM": ("США", "Financials"),
        "MAR-RM": ("США", "Consumer Discretionary"),
        "MAS-RM": ("США", "Industrials"),
        "MAT-RM": ("США", "Consumer Discretionary"),
        "MBGL-RM": ("США", "Industrials"),
        "MCD-RM": ("США", "Consumer Discretionary"),
        "MCHI-RM": ("Китай", "ETF"),
        "MCHP-RM": ("США", "Information Technology"),
        "MCO-RM": ("США", "Financials"),
        "MDRX-RM": ("США", "Health Care"),
        "MET-RM": ("США", "Financials"),
        "MGM-RM": ("США", "Consumer Discretionary"),
        "MGY-RM": ("США", "Energy"),
        "MKC-RM": ("США", "Consumer Staples"),
        "MMM-RM": ("США", "Industrials"),
        "MNST-RM": ("США", "Consumer Staples"),
        "MOMO-RM": ("Китай", "Communication Services"),
        "MOS-RM": ("США", "Materials"),
        "MPC-RM": ("США", "Energy"),
        "MQQ-RM": ("США", "Financials"),
        "MRK-RM": ("США", "Health Care"),
        "MRNA-RM": ("США", "Health Care"),
        "MS-RM": ("США", "Financials"),
        "MSCI-RM": ("США", "Financials"),
        "MSFT-RM": ("США", "Information Technology"),
        "MSI-RM": ("США", "Information Technology"),
        "MSTR-RM": ("США", "Information Technology"),
        "MTB-RM": ("США", "Financials"),
        "MTCH-RM": ("США", "Communication Services"),
        "MTG-RM": ("США", "Financials"),
        "MUR-RM": ("США", "Energy"),
        "NAVI-RM": ("США", "Financials"),
        "NCR-RM": ("США", "Information Technology"),
        "NDAQ-RM": ("США", "Financials"),
        "NEE-RM": ("США", "Utilities"),
        "NEM-RM": ("США", "Materials"),
        "NET-RM": ("США", "Information Technology"),
        "NFLX-RM": ("США", "Communication Services"),
        "NIO-RM": ("Китай", "Consumer Discretionary"),
        "NKE-RM": ("США", "Consumer Discretionary"),
        "NOV-RM": ("США", "Energy"),
        "NOW-RM": ("США", "Information Technology"),
        "NRDE-RM": ("США", "Industrials"),
        "NRG-RM": ("США", "Utilities"),
        "NTAP-RM": ("США", "Information Technology"),
        "NTLA-RM": ("США", "Health Care"),
        "NTNX-RM": ("США", "Information Technology"),
        "NUE-RM": ("США", "Materials"),
        "NVDA-RM": ("США", "Information Technology"),
        "NVS-RM": ("Швейцария", "Health Care"),
        "NWL-RM": ("США", "Consumer Discretionary"),
        "NWS-RM": ("США", "Communication Services"),
        "NYT-RM": ("США", "Communication Services"),
        "ODFL-RM": ("США", "Industrials"),
        "OGN-RM": ("США", "Health Care"),
        "OI-RM": ("США", "Materials"),
        "OKE-RM": ("США", "Energy"),
        "OKTA-RM": ("США", "Information Technology"),
        "OMC-RM": ("США", "Communication Services"),
        "ON-RM": ("США", "Information Technology"),
        "ORCL-RM": ("США", "Information Technology"),
        "ORLY-RM": ("США", "Consumer Discretionary"),
        "OSUR-RM": ("США", "Health Care"),
        "OTIS-RM": ("США", "Industrials"),
        "OVV-RM": ("Канада", "Energy"),
        "OXY-RM": ("США", "Energy"),
        "PANW-RM": ("США", "Information Technology"),
        "PATH-RM": ("США", "Information Technology"),
        "PAYC-RM": ("США", "Industrials"),
        "PBF-RM": ("США", "Energy"),
        "PBI-RM": ("США", "Industrials"),
        "PCAR-RM": ("США", "Industrials"),
        "PCG-RM": ("США", "Utilities"),
        "PD-RM": ("США", "Information Technology"),
        "PEG-RM": ("США", "Utilities"),
        "PEP-RM": ("США", "Consumer Staples"),
        "PFE-RM": ("США", "Health Care"),
        "PG-RM": ("США", "Consumer Staples"),
        "PGR-RM": ("США", "Financials"),
        "PHM-RM": ("США", "Consumer Discretionary"),
        "PINS-RM": ("США", "Communication Services"),
        "PKG-RM": ("США", "Materials"),
        "PLUG-RM": ("США", "Industrials"),
        "PM-RM": ("США", "Consumer Staples"),
        "PNC-RM": ("США", "Financials"),
        "PPG-RM": ("США", "Materials"),
        "PPL-RM": ("США", "Utilities"),
        "PRU-RM": ("США", "Financials"),
        "PSTG-RM": ("США", "Information Technology"),
        "PSX-RM": ("США", "Energy"),
        "PTC-RM": ("США", "Information Technology"),
        "PTON-RM": ("США", "Consumer Discretionary"),
        "PVH-RM": ("США", "Consumer Discretionary"),
        "PWR-RM": ("США", "Industrials"),
        "PYPL-RM": ("США", "Financials"),
        "QCOM-RM": ("США", "Information Technology"),
        "QRVO-RM": ("США", "Information Technology"),
        "QS-RM": ("США", "Consumer Discretionary"),
        "REGN-RM": ("США", "Health Care"),
        "RF-RM": ("США", "Financials"),
        "RJF-RM": ("США", "Financials"),
        "RL-RM": ("США", "Consumer Discretionary"),
        "ROK-RM": ("США", "Industrials"),
        "ROKU-RM": ("США", "Communication Services"),
        "ROST-RM": ("США", "Consumer Discretionary"),
        "RSG-RM": ("США", "Industrials"),
        "RTX-RM": ("США", "Industrials"),
        "RUN-RM": ("США", "Industrials"),
        "RVLV-RM": ("США", "Consumer Discretionary"),
        "S-RM": ("США", "Information Technology"),
        "SAP-RM": ("Германия", "Information Technology"),
        "SBUX-RM": ("США", "Consumer Discretionary"),
        "SCCO-RM": ("США", "Materials"),
        "SCHW-RM": ("США", "Financials"),
        "SEDG-RM": ("Израиль", "Information Technology"),
        "SFIX-RM": ("США", "Consumer Discretionary"),
        "SFM-RM": ("США", "Consumer Staples"),
        "SHLS-RM": ("США", "Industrials"),
        "SHW-RM": ("США", "Materials"),
        "SJM-RM": ("США", "Consumer Staples"),
        "SLDB-RM": ("США", "Health Care"),
        "SNA-RM": ("США", "Industrials"),
        "SNAP-RM": ("США", "Communication Services"),
        "SNPS-RM": ("США", "Information Technology"),
        "SO-RM": ("США", "Utilities"),
        "SONO-RM": ("США", "Consumer Discretionary"),
        "SONY-RM": ("Япония", "Consumer Discretionary"),
        "SPCE-RM": ("США", "Industrials"),
        "SPGI-RM": ("США", "Financials"),
        "SPY-RM": ("США", "ETF"),
        "SQ-RM": ("США", "Financials"),
        "SRE-RM": ("США", "Utilities"),
        "SRPT-RM": ("США", "Health Care"),
        "STLD-RM": ("США", "Materials"),
        "STT-RM": ("США", "Financials"),
        "STZ-RM": ("США", "Consumer Staples"),
        "SWK-RM": ("США", "Industrials"),
        "SWKS-RM": ("США", "Information Technology"),
        "SYF-RM": ("США", "Financials"),
        "SYK-RM": ("США", "Health Care"),
        "SYY-RM": ("США", "Consumer Staples"),
        "TAL-RM": ("Китай", "Consumer Discretionary"),
        "TDC-RM": ("США", "Information Technology"),
        "TDOC-RM": ("США", "Health Care"),
        "TDS-RM": ("США", "Communication Services"),
        "TER-RM": ("США", "Information Technology"),
        "TFC-RM": ("США", "Financials"),
        "TFX-RM": ("США", "Health Care"),
        "TGT-RM": ("США", "Consumer Discretionary"),
        "TJX-RM": ("США", "Consumer Discretionary"),
        "TM-RM": ("Япония", "Consumer Discretionary"),
        "TMO-RM": ("США", "Health Care"),
        "TMUS-RM": ("США", "Communication Services"),
        "TPR-RM": ("США", "Consumer Discretionary"),
        "TRIP-RM": ("США", "Consumer Discretionary"),
        "TRMB-RM": ("США", "Information Technology"),
        "TROW-RM": ("США", "Financials"),
        "TRV-RM": ("США", "Financials"),
        "TSLA-RM": ("США", "Consumer Discretionary"),
        "TSM-RM": ("Тайвань", "Information Technology"),
        "TSN-RM": ("США", "Consumer Staples"),
        "TSPH-RM": ("США", "Information Technology"),
        "TTD-RM": ("США", "Communication Services"),
        "TTWO-RM": ("США", "Communication Services"),
        "TWLO-RM": ("США", "Information Technology"),
        "TXN-RM": ("США", "Information Technology"),
        "U-RM": ("США", "Information Technology"),
        "UA-RM": ("США", "Consumer Discretionary"),
        "UAL-RM": ("США", "Industrials"),
        "UBER-RM": ("США", "Industrials"),
        "ULTA-RM": ("США", "Consumer Discretionary"),
        "UNH-RM": ("США", "Health Care"),
        "UNM-RM": ("США", "Financials"),
        "UNP-RM": ("США", "Industrials"),
        "UPWK-RM": ("США", "Industrials"),
        "URBN-RM": ("США", "Consumer Discretionary"),
        "URI-RM": ("США", "Industrials"),
        "USB-RM": ("США", "Financials"),
        "V-RM": ("США", "Financials"),
        "VFC-RM": ("США", "Consumer Discretionary"),
        "VIPS-RM": ("Китай", "Consumer Discretionary"),
        "VIRT-RM": ("США", "Financials"),
        "VLO-RM": ("США", "Energy"),
        "VMC-RM": ("США", "Materials"),
        "VNT-RM": ("США", "Industrials"),
        "VOO-RM": ("США", "ETF"),
        "VRTX-RM": ("США", "Health Care"),
        "VTRS-RM": ("США", "Health Care"),
        "VUZI-RM": ("США", "Information Technology"),
        "VXRT-RM": ("США", "Health Care"),
        "VZ-RM": ("США", "Communication Services"),
        "W-RM": ("США", "Consumer Discretionary"),
        "WAB-RM": ("США", "Industrials"),
        "WDAY-RM": ("США", "Information Technology"),
        "WDC-RM": ("США", "Information Technology"),
        "WEC-RM": ("США", "Utilities"),
        "WFC-RM": ("США", "Financials"),
        "WISH-RM": ("США", "Consumer Discretionary"),
        "WM-RM": ("США", "Industrials"),
        "WMB-RM": ("США", "Energy"),
        "WMT-RM": ("США", "Consumer Staples"),
        "WU-RM": ("США", "Financials"),
        "WYNN-RM": ("США", "Consumer Discretionary"),
        "XEL-RM": ("США", "Utilities"),
        "XLE-RM": ("США", "ETF"),
        "XOMM-RM": ("США", "Energy"),
        "XPEV-RM": ("Китай", "Consumer Discretionary"),
        "XPO-RM": ("США", "Industrials"),
        "XRX-RM": ("США", "Information Technology"),
        "YEXT-RM": ("США", "Information Technology"),
        "YUMC-RM": ("Китай", "Consumer Discretionary"),
        "Z-RM": ("США", "Real Estate"),
        "ZBH-RM": ("США", "Health Care"),
        "ZBRA-RM": ("США", "Information Technology"),
        "ZI-RM": ("США", "Industrials"),
        "ZIP-RM": ("США", "Industrials"),
        "ZM-RM": ("США", "Information Technology"),
        "ZS-RM": ("США", "Information Technology"),
        "ZTS-RM": ("США", "Health Care"),
    }

    def __init__(self) -> None:
        logger.debug("SectorStockForeignService initialized")

    def get_country(self, ticker: str) -> str:
        """Возвращает страну по тикеру."""
        if not ticker:
            return self.UNKNOWN_COUNTRY

        ticker = ticker.upper().strip()
        country_sector = self.COUNTRY_SECTOR_MAP.get(ticker)

        if country_sector:
            country = country_sector[0]
            logger.debug("COUNTRY FOUND TICKER=%s COUNTRY=%s", ticker, country)
            return country

        logger.debug("COUNTRY NOT FOUND TICKER=%s", ticker)
        return self.UNKNOWN_COUNTRY

    def get_sector(self, ticker: str) -> str:
        """Возвращает сектор (на русском языке) по тикеру."""
        if not ticker:
            return self.UNKNOWN_SECTOR

        ticker = ticker.upper().strip()
        country_sector = self.COUNTRY_SECTOR_MAP.get(ticker)

        if country_sector:
            gics_sector = country_sector[1]
            sector_ru = self.GICS_TO_RUSSIAN.get(gics_sector, gics_sector)
            logger.debug("SECTOR FOUND TICKER=%s SECTOR=%s", ticker, sector_ru)
            return sector_ru

        logger.debug("SECTOR NOT FOUND TICKER=%s", ticker)
        return self.UNKNOWN_SECTOR

    def enrich(self, stock: StockModel) -> StockModel:
        """Добавляет страну и сектор в StockModel."""
        stock.country = self.get_country(stock.secid)
        stock.sector = self.get_sector(stock.secid)
        return stock